### ISSUE TITLE
Need updates to artifacts/compatibility-yaml

### ISSUE THREAD

**Issue by sashrith** [vmware-tanzu/vsphere-kubernetes-drivers-operator#157]
**Issue/Feature Description:** Need updates for https://github.com/vmware-tanzu/vsphere-kubernetes-drivers-operator/blob/main/artifacts/compatibility-yaml/compatibility-v0.2.1.yaml

**What type of Issue/Feature is this?**
/kind bug fix

**Why this fix/ feature is needed(give scenarios or use cases):**
Some fixes are required for the compatibility yaml file

```yaml
"2.5.1": {
      "vSphere": { "min": "6.7.1", "max": "7.0.4" },
      "k8s": { "min": "1.20", "max": "1.23" },
      "isCPIRequired": false,
      "deploymentPath": [
          "https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.5.1/manifests/vanilla/vsphere-csi-driver.yaml" ]
    },
```

should be 
```yaml
"2.5.1": {
      "vSphere": { "min": "6.7.1", "max": "7.0.4" },
      "k8s": { "min": "1.21", "max": "1.23" },               <----
      "isCPIRequired": false,
      "deploymentPath": [
          "https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.5.1/manifests/vanilla/vsphere-csi-driver.yaml" ]
    },
```

and vsphere version should be >6.7u3 for all CSI releases, not sure if "6.7.1" covers that correctly

CPI manifests should be taken from https://github.com/kubernetes/cloud-provider-vsphere/tree/master/releases/<version>/vsphere-cloud-controller-manager.yaml

CPI manifests from the following path are deprecated,
https://github.com/kubernetes/cloud-provider-vsphere/tree/master/manifests/controller-manager -
